# This is a basic workflow to help you get started with Actions
name: CI-CD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains multiple jobs
  build_test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      # install applicaion dependencies
      - name: Install dependencies
        run: |
          npm install
          # npm ci

      # Install Postman CLI
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

      # install nodemon
      - name: Install nodemon
        run: npm install -g nodemon

      # # install newman-reporter-htmlextra
      # - name: Install newman reporter htmlextra
      #   run: npm install -g newman-reporter-htmlextra

      - name: Run the API and Postman's tests
        run: |
          nodemon &
          sleep 20
          postman collection run "helloWorld.postman_collection.json" 

      
          # name: Automated API tests using Postman CLI

          # on: push
          
          # jobs:
          #   automated-api-tests:
          #     runs-on: ubuntu-latest
          #     steps:
          #       - uses: actions/checkout@v3
          #       - name: Install Postman CLI
          #         run: |
          #           curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
          #       - name: Login to Postman CLI
          #         run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
          #       - name: Run API tests
          #         run: |
          #           postman collection run "DIMANEX_API.postman_collection.json"